dist: bionic

language: elixir

elixir:
  - 1.11

otp_release:
  - 23.1

cache:
  directories:
    - deps
    - _build

addons:
  postgresql: 11

services:
  - postgresql

before_script:
  - npm install --prefix priv/embed
